FROM ubuntu:22.04

# Copiez le fichier source dans le conteneur
COPY http_server.c /

# Définissez le répertoire de travail
WORKDIR /

# Installez le compilateur GCC
RUN apt-get update && apt-get install -y gcc

# Compilez l'application
RUN gcc -o fibonacci http_server.c

# Commande par défaut à exécuter lorsque le conteneur démarre
CMD ["/fibonacci"]