FROM ubuntu:22.04
# FILETESTMODE can be either Rndrd, Rndwr, Seqwr, Seqrd

RUN apt-get update && \
    apt-get install -y sysbench

RUN sysbench fileio prepare

ENTRYPOINT ["sysbench", "fileio","--file-test-mode=seqrd", "run"]